UNIFORM_OPERATION_FAIL = "Operation failed"
UNIFORM_ACCESS_DENIED = "Access denied"
MAX_INPUT_ATTEMPTS = 3
LIVENESS_DETECTION_ENABLED = True

HIGH_SECURITY_THRESHOLD = 0.85

# Rate limiting constants
MAX_AUTH_ATTEMPTS_PER_HOUR = 3
COOLDOWN_PERIOD_SECONDS = 90 

# Time constants (in seconds)
SECONDS_PER_DAY = 86400
SECONDS_PER_WEEK = 604800
SECONDS_PER_HOUR = 3600